### ISSUE TITLE
Can we use multiple baseestimators?

### ISSUE THREAD

**Issue by EternalConfession** [xuyxu/Ensemble-Pytorch#49]
In the demo and DOCs, it seems that we can only use one type of model as basemodel.

Can we use different models as base estimators?

**Comment by xuyxu** [comment]
Hi @EternalConfession, I think you are referring to heterogeneous ensemble.

This feature request is still on-going, mainly because training protocols on different base estimators could be quite different, and therefore needs careful design.

**Comment by EternalConfession** [comment]
> Hi @EternalConfession, I think you are referring to heterogeneous ensemble.
> 
> This feature request is still on-going (#40), mainly because training protocols on different base estimators could be quite different, and therefore needs careful design.

Thanks for your reply.

Is there any related work on heterogeneous ensemble methods?

**Comment by xuyxu** [comment]
Here are two related papers published in MLSys 2020, which are related to building heterogeneous ensembles on top of the neural network:

* [MotherNets: Rapid Deep Ensemble Learning](https://proceedings.mlsys.org/paper/2020/file/3ef815416f775098fe977004015c6193-Paper.pdf)
* [FLEET: Flexible Efficient Ensemble Training for Heterogeneous Deep Neural Networks](https://proceedings.mlsys.org/paper/2020/file/ed3d2c21991e3bef5e069713af9fa6ca-Paper.pdf)

In my point of view, recent works tend to focus more on how to reduce the training costs on the ensemble, especially when using large neural networks as the base estimator. Research on novel ensemble algorithms is lacking in recent years. Correct me if you have other opinions ;-)

**Comment by xuyxu** [comment]
Closed due to inactivity.
