### ISSUE TITLE
Pytorch Model Usage [Support model validation and serialization]

### ISSUE THREAD

**Issue by ozanpkr** [xuyxu/Ensemble-Pytorch#6]
Hi @xuyxu ,
    I wanna use this repo with pytorch cnn models such as resnet,densenet,etc. Can I use this repo for that?I tried but I got error.After then I  created ensemble model with two submodel(hrnet_w18_small).When I use this ensemble model with your repo I got error again 😄 Have you any suggestion? 

```
m1 = timm.create_model('hrnet_w18_small', pretrained=False)
m2=timm.create_model('hrnet_w18_small', pretrained=False)
```

```
m1.classifier = nn.Sequential(nn.Linear(2048, 2), nn.Sigmoid())
m2.classifier = nn.Sequential(nn.Linear(2048, 2), nn.Sigmoid())

```
```
m1.load_state_dict(torch.load('./hr18_1.pth'))
m2.load_state_dict(torch.load('./hr18_2.pth'))
```

```
class MyEnsemble(nn.Module):
    def __init__(self,nb_classes=2):
        super(MyEnsemble, self).__init__()
        self.modelA = m1
        self.modelB = m2
        self.classifier =nn.Linear(2, 2)

    def forward(self,x):
        x1 = self.modelA(x)
        x1 = x1.view(x1.size(0), -1)
        x2 = self.modelB(x)
        x2 = x2.view(x2.size(0), -1)
        x = torch.cat((x1, x2), dim=1)
        x = self.classifier(torch.softmax(x, dim=1))
        return x
```

```
model = FusionClassifier(
        estimator=myens,
        n_estimators=n_estimators,
        cuda=True
    )

model.fit(dataloaders['train'],
          lr=1e-3,
          weight_decay=5e-4,
          epochs=10)

model.fit(dataloaders['train'], lr, weight_decay, epochs, "Adam")
```

> TypeError                                 Traceback (most recent call last)
> <ipython-input-16-b7b5e5b0fa5e> in <module>
>       1 tic = time.time()
> ----> 2 model.fit(dataloaders['train'], lr, weight_decay, epochs, "Adam")
>       3 toc = time.time()
>       4 training_time = toc - tic

> ~\Desktop\Ensemble-Pytorch-master\torchensemble\fusion.py in fit(self, train_loader, lr, weight_decay, epochs, optimizer, log_interval)
>      77         # Instantiate base estimators and set attributes
>      78         for _ in range(self.n_estimators):
> ---> 79             self.estimators_.append(self._make_estimator())
>      80         self.n_outputs = self._decide_n_outputs(train_loader, True)
>      81         optimizer = utils.set_optimizer(self, optimizer, lr, weight_decay)
> 
> ~\Desktop\Ensemble-Pytorch-master\torchensemble\_base.py in _make_estimator(self)
>      86         """Make and configure a copy of the `base_estimator_`."""
>      87         if self.estimator_args is None:
> ---> 88             estimator = self.base_estimator_()
>      89         else:
>      90             estimator = self.base_estimator_(**self.estimator_args)
> 
> ~\anaconda3\envs\pytorchenv\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
>     725             result = self._slow_forward(*input, **kwargs)
>     726         else:
> --> 727             result = self.forward(*input, **kwargs)
>     728         for hook in itertools.chain(
>     729                 _global_forward_hooks.values(),
> 
> TypeError: forward() missing 1 required positional argument: 'x'

**Comment by xuyxu** [comment]
Hi @ghost-ronin, thanks for reporting!

What is the type of `myens` in your fifth code snippet when initializing the `FusionClassifier` ? If it is an instantiation of your class `MyEnsemble`, then I think the problem is that your should directly pass `MyEnsemble` to `FusionClassifier` :-)

Would you please try whether the solution above fixes your problem, and I will follow up this issue.

**Comment by ghost-ronin** [comment]
> Hi @ghost-ronin, thanks for reporting!
> 
> What is the type of `myens` in your fifth code snippet when initializing the `FusionClassifier` ? If it is an instantiation of your class `MyEnsemble`, then I think the problem is that your should directly pass `MyEnsemble` to `FusionClassifier` :-)
> 
> Would you please try whether the solution above fixes your problem, and I will follow up this issue.
> 
> **EDIT**: This problem may be similar to yours issue #4.

Hi @xuyxu ,
    I have got good train acc score with pytorch -models on your code.I created new class taht include models feature.This code is;
```
model_1 =models.resnet18(pretrained=True)
model_1.fc = nn.Sequential(nn.Linear(512, 2),
nn.Sigmoid())

model_1=nn.Sequential(*list(model_1.children())[:-1])

class new_net(nn.Module):
    def __init__(self):
        super(new_net, self).__init__()

        self.model_1 = model_1
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, 128)
        self.fc5 = nn.Sequential(nn.Linear(128, 2))

    def forward(self, X):

        output = self.model_1(X)
        output = output.view(-1, self.num_flat_features(output))
        output = F.relu(self.fc2(output))
        output = F.dropout(output)
        output = F.relu(self.fc3(output))
        output = F.dropout(output)
        output = self.fc5(output)

        return output
    
    def num_flat_features(self, X):
        size = X.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s

        return num_features
model = FusionClassifier(
        estimator=new_net,
        n_estimators=2,
        cuda=True,
        n_jobs=1 )
```
Now I have suggestion to you 😄 Can you try create one function that calculate train acc,train loss and val acc val loss for save best val acc weight and avoid on overfitting ?I tried that but without gpu usage optimization. So it was not user-friendly 😄 I tried write like that;
```
def train_model(model, criterion, optimizer, scheduler, num_epochs):
    since = time.time()
    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0
    ghost=True
    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch, num_epochs - 1))
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['train', 'val']:
            if phase == 'train':
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            running_corrects = 0

            # Iterate over data.
            for inputs, labels in dataloaders[phase]:
                inputs = inputs.to(device)
                labels = labels.to(device)

                # zero the parameter gradients
                optimizer.zero_grad()

                # forward
                # track history if only in train
                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs)
                    _, preds = torch.max(outputs, 1)
                    loss = criterion(outputs, labels)

                    # backward + optimize only if in training phase
                    if phase == 'train':
                        loss.backward()
                        optimizer.step()

                # statistics
                running_loss += loss.detach() * inputs.size(0) #.item()
                running_corrects += torch.sum(preds == labels.data)
            if phase == 'train':
                scheduler.step()

            epoch_loss = running_loss/ dataset_sizes[phase]
            epoch_acc = running_corrects.double() / dataset_sizes[phase]
            
            #Losses and accuracy per epochs are stored in array for plot graphs
            if phase == 'train':              
                train_losses.append(epoch_loss)
                train_acc.append(epoch_acc)
                print('{} Loss: {:.4f} Acc: {:.4f}'.format(
                phase, epoch_loss, epoch_acc))
            if phase == 'val':
                print('{} Loss: {:.4f} Acc: {:.4f}'.format(
                phase, epoch_loss, epoch_acc))
                val_losses.append(epoch_loss)
                val_acc.append(epoch_acc)
                #early_stopping(epoch_loss, model)    
            torch.cuda.empty_cache()
            # deep copy the model
            if phase == 'val' and epoch_acc > best_acc:
                best_acc = epoch_acc
                best_model_wts = copy.deepcopy(model.state_dict())            
        print()
        torch.cuda.empty_cache()
    # Determine total traning time
    time_elapsed = time.time() - since
    print('Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60))    
    # Print best validation accuracy 
    print('Best val Acc: {:4f}'.format(best_acc))
    # load best model weights
    model.load_state_dict(best_model_wts)
    torch.save(best_model_wts, "/zzz.pth")
    return model
```

**Comment by xuyxu** [comment]
Hi @ghost-ronin, glad to see your problem solved, and thanks for your suggestions!

I will pin this issue and work on it latter ;-)

**Comment by ghost-ronin** [comment]
Hi @xuyxu .
I have news for you 😄  I recreate fussionclassifier that include validation step.You can your repo after check.I used that and I didn't see any problem.
You send dataloader dict. that has train and validation dataset.After all epoch this function save best weight on your machine and load your model finally return val train acc loss list for draw graphs 😃  next task is add learning rate scheduler :D

class FusionClassifier(BaseModule):
    """Implementation of the FusionClassifier."""

    def _forward(self, X):
        """
        Implementation on the internal data forwarding in FusionClassifier.
        """
        batch_size = X.size()[0]
        proba = torch.zeros(batch_size, self.n_outputs).to(self.device)

        # Take the average over predictions from all base estimators.
        for estimator in self.estimators_:
            proba += estimator(X) / self.n_estimators

        return proba

    def forward(self, X):
        """
        Implementation on the data forwarding in FusionClassifier.

        Parameters
        ----------
        X : tensor
            Input batch of data, which should be a valid input data batch for
            base estimators.

        Returns
        -------
        proba : tensor of shape (batch_size, n_classes)
            The predicted class distribution.
        """
        proba = self._forward(X)

        return F.softmax(proba, dim=1)

    def fit(self,
            dataloaders,
            lr=1e-3,
            weight_decay=5e-4,
            epochs=100,
            optimizer="Adam",
            log_interval=100):
        train_losses = []
        train_acc = []
        val_losses = []
        val_acc = []
        best_model_wts=[]
        criterion = nn.CrossEntropyLoss()
        since = time.time()
        best_model_wts=copy.deepcopy(self.state_dict())
        best_acc = 0.0
        for _ in range(self.n_estimators):
            self.estimators_.append(self._make_estimator())
        self.n_outputs = self._decide_n_outputs(dataloaders['train'], True)
        optimizer = utils.set_optimizer(self, optimizer, lr, weight_decay)
        self._validate_parameters(lr, weight_decay, epochs, log_interval)
        for epoch in range(epochs):
            print('Epoch {}/{}'.format(epoch, epochs - 1))
            print('-' * 10)

            # Each epoch has a training and validation phase
            for phase in ['train', 'val']:
                if phase == 'train':
                    
                    self.train()  # Set model to training mode
                else:
                    self.eval()  # Set model to evaluate mode

                running_loss = 0.0
                running_corrects = 0

                # Iterate over data.
                for batch_idx, (data, target) in enumerate(dataloaders[phase]):

                    data = data.to(self.device)
                    target = target.to(self.device)

                    # zero the parameter gradients
                    optimizer.zero_grad()

                    # forward
                    # track history if only in train
                    with torch.set_grad_enabled(phase == 'train'):
                        outputs = self._forward(data)
                        _, preds = torch.max(outputs, 1)
                        loss = criterion(outputs, target)

                        # backward + optimize only if in training phase
                        if phase == 'train':
                            
                            loss.backward()
                            optimizer.step()

                    # statistics
                    running_loss += loss.detach() * data.size(0)  # .item()
                    running_corrects += torch.sum(preds == target.data)

                if phase == 'train':
                    size=8379#train dataset size.you can be dynamic with basic operation
                if phase == 'val':
                    size=563

                epoch_loss = running_loss / size
                epoch_acc = running_corrects.double() / size

                # Losses and accuracy per epochs are stored in array for plot graphs
                if phase == 'train':
                    train_losses.append(epoch_loss)
                    train_acc.append(epoch_acc)
                    print('{} Loss: {:.4f} Acc: {:.4f}'.format(
                        phase, epoch_loss, epoch_acc))
                if phase == 'val':
                    print('{} Loss: {:.4f} Acc: {:.4f}'.format(
                        phase, epoch_loss, epoch_acc))
                    val_losses.append(epoch_loss)
                    val_acc.append(epoch_acc)
                torch.cuda.empty_cache()

                if phase == 'val' and epoch_acc > best_acc:
                    best_acc = epoch_acc
                    best_model_wts=copy.deepcopy(self.state_dict())
          

            print()
            torch.cuda.empty_cache()
        # Determine total traning time
        time_elapsed = time.time() - since
        print('Training complete in {:.0f}m {:.0f}s'.format(
            time_elapsed // 60, time_elapsed % 60))

        # Print best validation accuracy 
        print('Best val Acc: {:4f}'.format(best_acc))

        self.load_state_dict(best_model_wts)
        torch.save(best_model_wts, "./ourwegiht.pth")
        return train_losses,train_acc,val_losses,val_acc

**Comment by xuyxu** [comment]
Thanks @ghost-ronin! I like your way of integrating both of validation and serialization into the `fit`. In addition, I have two small problems on your code snippet above:

(1) How is the variable `phase` passed to the `fit` ? It looks like it is not an input argument of the function `fit`;
(2) What is the type of `dataloaders` as the first input argument of `fit`?

* * *

Besides, here are some of my thoughts on this feature request, and I will appreciate it very much to have your advice before refactoring.

 The new `fit` function looks like this:

``` python
def fit(self,
        train_loader,
        lr=1e-3,
        weight_decay=5e-4,
        epochs=100,
        optimizer="Adam",
        log_interval=100,
        test_loader=None,
        save_model=True,
        save_dir=None):
```
**Meaning of newly added parameters:**
* `test_loader`
    * If `test_loader` is not `None`, model validation on the `test_loader` after each training epoch is conducted;
    * If `test_loader` is `None`, no model validation is conducted.
* `save_model`
    * If `test_loader` is not `None`, we will save the model with the best validation accuracy;
    * If `test_loader` is `None`, we directly save the fully trained model.
* `save_dir`: Specify the directory of the dumped model;

Looking forward to your reply ;-)

**Comment by ghost-ronin** [comment]
Hi @xuyxu ,
In every epoch we use for loop on 'train' and 'val' string like that;
```
for phase in ['train', 'val']:
```
For second question we use dataloaders like that;

```
pretrained_size = 320

pretrained_means = [0.485,0.456,0.406]

pretrained_stds= [0.229,0.224,0.225]

batch_size=8

data_transforms = {
    
    'train': transforms.Compose([
        transforms.Resize((pretrained_size,pretrained_size)),
                           transforms.RandomHorizontalFlip(),
                           transforms.RandomRotation(10),
                           transforms.ToTensor(),
                           transforms.Normalize(mean = pretrained_means, 
                                                std = pretrained_stds)
    ]),
    'val': transforms.Compose([
        transforms.Resize((pretrained_size,pretrained_size)),
                           transforms.ToTensor(),
                           transforms.Normalize(mean = pretrained_means, 
                                                std = pretrained_stds)
    ]),
                   }
print("Initializing Datasets and Dataloaders...\n")
# Create training and validation datasets
image_datasets = {x: datasets.ImageFolder(os.path.join(data_dir, x), data_transforms[x]) for x in ['train', 'val']}
# Create training and validation dataloaders
dataloaders = {x: torch.utils.data.DataLoader(image_datasets[x], batch_size=batch_size, shuffle=True, num_workers=4,pin_memory=True) for x in ['train', 'val']}
# Detect if we have a GPU available
device = torch.device("cuda:0")
#device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
dataset_sizes ={x:len(image_datasets[x]) for x in ['train','val']}
```
Finally your new fit function is looks great with new parameters 💯

**Comment by xuyxu** [comment]
Thanks for your explaination @ghost-ronin. My last question is that would it be convenient for you to report the improved performance after using `fusionclassifier`?

It looks like you are using `ResNet18` as the base estimator, which is quite large, complex, and powerful. Therefore, I am interesting to know that how much improvements could be achieved by `fusionclassifier` when using this kind of base estimator :D

**Comment by ghost-ronin** [comment]
> Thanks for your explaination @ghost-ronin. My last question is that would it be convenient for you to report the improved performance after using `fusionclassifier`?
> 
> It looks like you are using `ResNet18` as the base estimator, which is quite large, complex, and powerful. Therefore, I am interesting to know that how much improvements could be achieved by `fusionclassifier` when using this kind of base estimator :D

I would be pleased to share the effect of fusion classification on performance.However ,my dataset is little hard.So ,I will try on  your fusion classifier with easy datas after then my project.

**Comment by xuyxu** [comment]
Never mind, gook luck with your project !

Meanwhile, I will keep this issue open and upload the improved version in a few days.

**Comment by ghost-ronin** [comment]
Not a subject to be ignored 😄 I write academic paper so I have little time .I wanna know that effects of your repo on other dataset.So I will try it and share with you.

**Comment by xuyxu** [comment]
Hi @ghost-ronin,  this feature request has been added to the master branch. You can use it according to instructions in https://ensemble-pytorch.readthedocs.io/en/latest/parameters.html.

I will keep this issue open, and feel free to comment on this feature request if you have any problem ;-)

**Comment by xuyxu** [comment]
Hi @ozanpkr, I have not heard from you for a while.

This issue has already been fixed, you can check the changelog for details: https://ensemble-pytorch.readthedocs.io/en/latest/changelog.html. Feel free to re-open the issue if you still have any problem ;-)
