### ISSUE TITLE
How to load a saved ensemble

### ISSUE THREAD

**Issue by mpierrau** [xuyxu/Ensemble-Pytorch#66]
Hi! 

Thank you for a nice ensemble wrapper!

I can't seem to figure out how to load a saved model and there are no instructions in the docs on this process. I have tried to use `load_state_dict` with the loaded state dictionary, but I get a RuntimeError (missing keys). So performing:
```
kwargs = {'pretrained':False, 'num_classes' = 9}

model = VotingClassifier(models.mobilenet_v2(kwargs),5,True)
model.set_optimizer("Adam", lr=1e-3, weight_decay=5e-4)
model.fit(train_dl, epochs=10)
```

and then

```
d = torch.load('VotingClassifier_MobileNetV2_5_ckpt.pth')
model2 = VotingClassifier(models.mobilenet_v2(kwargs),5,True)
model2.load_state_dict(d)
```

gives the error

```
RuntimeError: Error(s) in loading state_dict for MobileNetV2:
	Missing key(s) in state_dict: "features.0.0.weight", "features.0.1.weight", "features.0.1.bias", "features.0.1.running_mean", "features.0.1.running_var", "features.1.conv.0.0.weight", "features.1.conv.0.1.weight", "features.1.conv.0.1.bias", "features.1.conv.0.1.running_mean", "features.1.conv.0.1.running_var", "features.1.conv.1.weight", "features.1.conv.2.weight", "features.1.conv.2.bias", "features.1.conv.2.running_mean", "features.1.conv.2.running_var", "features.2.conv.0.0.weight", "features.2.conv.0.1.weight", "features.2.conv.0.1.bias", "features.2.conv.0.1.running_mean", "features.2.conv.0.1.running_var", "features.2.conv.1.0.weight", ...
```
etc.

I have tried to load the dict to the individual base learners as well as loading `d['model']`, but without success.

Hoping you can help!

Thank you!

**Comment by xuyxu** [comment]
Hi @mpierrau, the `test_clf_class` fucnction in [test_all_models.py](https://github.com/xuyxu/Ensemble-Pytorch/blob/master/torchensemble/tests/test_all_models.py) shows an example on how to save and re-load ensmebles.

Feel free to tell me if you have any problem.

**Comment by mpierrau** [comment]
Hi @xuyxu!

Thank you for your prompt reply and thank you for the pointer. I managed to load a saved model using the `io.load` module from `torchensemble.utils`. 

Since this is a highly utilized function, I think your documentation would benefit from including this.

Thanks for the help! :)

**Comment by xuyxu** [comment]
Sure, we will add this. Glad to hear that your problem solved.
